version: '2.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "${DATABASE_PORT}"
    volumes:
       - mongo:/data/mongo
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"